#!/bin/bash
# $Id: mkhello,v 1.1 2016-01-14 23:16:35-08 - - $
# Manav Sharma msharma7
cid hello.java
javac hello.java
echo Main-class: hello >Manifest
jar cvfm hello Manifest hello.class
chmod +x hello
rm Manifest hello.class
